CREATE TABLE reviews (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    placeid TEXT NOT NULL,
    placename TEXT NOT NULL,
    season TEXT NOT NULL,
    timeofday TEXT NOT NULL,
    rating INTEGER NOT NULL,
    reviewBody TEXT NOT NULL,
    reviewdate TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP,
    userid INTEGER REFERENCES users(id)
        ON DELETE CASCADE NOT NULL
);