INSERT INTO reviews (username, placeid, season, timeOfDay, rating, reviewBody, userid)
VALUES
('test', 'ChIJQwRohxBbwokRmHrfAMb3ixc', 'Fall', 'Morning', '5', 'I had such a wonderful time at this place! It was beautiful and quiet.', '1'),
('TestUser2', 'ChIJQwRohxBbwokRmHrfAMb3ixc', 'Spring', 'Evening', '3', 'I am in a morotized wheelchair and found the paths rather difficult to navigate.', '2'),
('TestUser3', 'ChIJQwRohxBbwokRmHrfAMb3ixc', 'Summer', 'Afternoon', '1', 'It was very difficult to find a quiet place to rest here.', '3'),
('test', 'ChIJZRdCJptbwokRz1kjJswgHWA', 'Fall', 'Morning', '5', 'This place was great!', '1'),
('TestUser2', 'ChIJyTmcRApbwokR', 'Spring', 'Evening', '3', 'I am in a morotized wheelchair and found the paths rather difficult to navigate.', '2'),
('TestUser3', 'ChIJnWjS-wRbwokRpCq5RGEIH3E', 'Summer', 'Afternoon', '1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '3'),
('TestUser3', 'ChIJwYu_aA5bwokR2lxjW', 'Summer', 'Afternoon', '1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '3'),
('TestUser3', 'ChIJzYGq1AlbwokR5rnEbWm1UxA', 'Summer', 'Afternoon', '1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '3'),
('TestUser3', 'ChIJQwRohxBbwokRmHrfAMb3ixc', 'Summer', 'Afternoon', '1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '3'),
('TestUser3', 'ChIJpdzbNqhbwokRCTFVMvjlGcw', 'Summer', 'Afternoon', '1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '3')
;